In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', 21)
dados = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Modulo-1/Regressao-Linear/kc_house_data.csv')
dados.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

**Excluindo algumas variaveis desnecessárias **

In [ ]:
dados.drop('id', axis = 1, inplace = True)
dados.drop('date', axis = 1, inplace = True)
dados.drop('zipcode', axis = 1, inplace = True)
dados.drop('lat', axis = 1, inplace = True)
dados.drop('long', axis = 1, inplace = True)

dados.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,1690,7639
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,1800,7503

In [ ]:
print(dados.shape)

(21613, 16)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

y = dados['price']
x = dados.drop(['price'], axis = 1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=14)

**Criando o modelo**

In [ ]:
modelo = LinearRegression()
modelo.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Calculando coeficiente R2**

In [ ]:
resultado = modelo.score(X_test, y_test)
print(resultado)

0.6538094196281105

**TESTANDO COM O MODELO LINEAR 'RIDGE REGRESSION'**

In [ ]:
from sklearn.linear_model import Ridge
modeloRidge = Ridge(alpha=10)
modeloRidge.fit(X_train, y_train)
resultadoRidge = modeloRidge.score(X_test, y_test)
print(resultadoRidge)

0.6545037069731696

**TESTATNDO COM O MODELO LINEAR 'LASSO' REGULARIZAÇAO L1**

In [ ]:
from sklearn.linear_model import Lasso
modeloLasso = Lasso(alpha=1000, max_iter = 1000, tol = 0.1)
modeloLasso.fit(X_train, y_train)
resultadoLasso = modeloLasso.score(X_test, y_test)
print(resultadoLasso)

0.6547706041742776

**TESTANDO COM ELASTIC NET**

In [ ]:
from sklearn.linear_model import ElasticNet
modeloElasticNet = ElasticNet(alpha=1, l1_ratio = 0.9, max_iter = 5000, tol = 0.2)
modeloElasticNet.fit(X_train, y_train)
resultadoElasticNet = modeloElasticNet.score(X_test, y_test)
print(resultadoElasticNet)

0.6429961330013114